import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/Northeastern-University-Seal-Logo.png',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        url: '/Northeastern-University-Seal-Logo.png',
        sizes: '16x16',
        type: 'image/png',
      }
    ],
    shortcut: '/Northeastern-University-Seal-Logo.png',
    apple: '/Northeastern-University-Seal-Logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-grad h-screen text-white flex items-center
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
